/-
We implement the explicit Euler method for ODEs and prove its convergence.

Definitions:
- `eulerStep`: A single step of the Euler method.
- `eulerPoint`: The sequence of points generated by the Euler method.
- `eulerPath`: The piecewise linear interpolation of the Euler points.
- `eulerDeriv`: The right derivative of the Euler path.

Theorems:
- `eulerPath_grid_point`: The Euler path coincides with the Euler points at grid points.
- `eulerPath_continuous`: The Euler path is continuous.
- `eulerPath_hasDerivWithinAt`: The Euler path has the expected right derivative.
- `eulerPath_eq_on_Ico`: Explicit formula for the Euler path on intervals.
- `eulerDeriv_eq_on_Ico`: Explicit formula for the Euler derivative on intervals.
- `euler_dist_point_path`: Bound on the distance between the Euler point and the path.
- `euler_derivative_bound`: Local bound on the difference between the Euler derivative and the vector field.
- `euler_derivative_global_bound`: Global bound on the difference between the Euler derivative and the vector field.
- `euler_error_bound`: Error bound for the Euler method using Gronwall's inequality.
- `euler_convergence`: The Euler method converges to the true solution as the step size goes to zero.
-/

import Mathlib.Analysis.ODE.Gronwall

set_option linter.mathlibStandardSet false

/--
The Euler step for an ODE y' = v(t, y) with step size h is y_{n+1} = y_n + h * v(t_n, y_n).
-/
def eulerStep {𝕜 : Type*} {E : Type*} [Ring 𝕜] [AddCommGroup E] [Module 𝕜 E] (v : 𝕜 → E → E) (h : 𝕜) (t : 𝕜) (y : E) : E :=
  y + h • v t y

/--
The n-th point in the Euler method approximation with step size h.
-/
def eulerPoint {𝕜 : Type*} {E : Type*} [Ring 𝕜] [AddCommGroup E] [Module 𝕜 E] (v : 𝕜 → E → E) (h : 𝕜) (t0 : 𝕜) (y0 : E) : ℕ → E
| 0 => y0
| n + 1 => eulerStep v h (t0 + n * h) (eulerPoint v h t0 y0 n)

/--
The piecewise linear path interpolating the Euler method points.
-/
noncomputable def eulerPath {𝕜 : Type*} {E : Type*} [Field 𝕜] [PartialOrder 𝕜] [FloorSemiring 𝕜]
    [AddCommGroup E] [Module 𝕜 E]
  (v : 𝕜 → E → E) (h : 𝕜) (t0 : 𝕜) (y0 : E) (t : 𝕜) : E :=
  let n := Nat.floor ((t - t0) / h)
  let tn := t0 + n * h
  let yn := eulerPoint v h t0 y0 n
  yn + (t - tn) • v tn yn

/-
The Euler path coincides with the Euler points at the grid points.
-/
theorem eulerPath_grid_point {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  (v : ℝ → E → E) (h : ℝ) (h_pos : 0 < h) (t0 : ℝ) (y0 : E) (n : ℕ) :
  eulerPath v h t0 y0 (t0 + n * h) = eulerPoint v h t0 y0 n := by
    unfold eulerPath; norm_num [add_sub_cancel_left, h_pos.ne']

private theorem floor_eq_of_mem_Ico (h_pos : 0 < h) (t0 : ℝ) (n : ℕ) (t : ℝ)
  (ht : t ∈ Set.Ico (t0 + n * h) (t0 + (n + 1) * h)) :
  ⌊(t - t0) / h⌋₊ = n :=
  Nat.floor_eq_on_Ico n _ ⟨by rw [le_div_iff₀ h_pos]; linarith [ht.1],
    by rw [div_lt_iff₀ h_pos]; linarith [ht.2]⟩

/--
The derivative of the Euler path (defined as the right derivative everywhere).
-/
noncomputable def eulerDeriv {𝕜 : Type*} {E : Type*} [Field 𝕜] [PartialOrder 𝕜] [FloorSemiring 𝕜]
    [AddCommGroup E] [Module 𝕜 E]
  (v : 𝕜 → E → E) (h : 𝕜) (t0 : 𝕜) (y0 : E) (t : 𝕜) : E :=
  let n := Nat.floor ((t - t0) / h)
  let tn := t0 + n * h
  let yn := eulerPoint v h t0 y0 n
  v tn yn

/-
The Euler path is continuous on each grid interval [t₀ + n*h, t₀ + (n+1)*h].
-/
private theorem eulerPath_continuousOn_Icc {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  (v : ℝ → E → E) (h : ℝ) (h_pos : 0 < h) (t0 : ℝ) (y0 : E) (n : ℕ) :
  ContinuousOn (eulerPath v h t0 y0) (Set.Icc (t0 + n * h) (t0 + (n + 1) * h)) := by
    set f := fun t => eulerPoint v h t0 y0 n + (t - (t0 + n * h)) • v (t0 + n * h) (eulerPoint v h t0 y0 n)
    suffices h_eq : Set.EqOn (eulerPath v h t0 y0) f (Set.Icc (t0 + n * h) (t0 + (n + 1) * h)) from
      (by fun_prop : ContinuousOn f _).congr h_eq
    intro t ht
    rcases eq_or_lt_of_le ht.2 with rfl | h_lt
    · -- Right endpoint: both equal y_{n+1}
      show _ = f _; simp only [f]
      have := eulerPath_grid_point v h h_pos t0 y0 (n + 1)
      simp only [Nat.cast_add, Nat.cast_one] at this
      rw [this]; simp [eulerStep, eulerPoint]; module
    · -- Left endpoint or interior: floor = n
      show _ = f t; simp only [f, eulerPath]
      rw [floor_eq_of_mem_Ico h_pos t0 n t ⟨ht.1, h_lt⟩]

/-
The Euler path is continuous on [t0, ∞).
-/
theorem eulerPath_continuous {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  (v : ℝ → E → E) (h : ℝ) (h_pos : 0 < h) (t0 : ℝ) (y0 : E) :
  ContinuousOn (eulerPath v h t0 y0) (Set.Ici t0) := by
    have h_cover : Set.Ici t0 ⊆ ⋃ n : ℕ, Set.Icc (t0 + n * h) (t0 + (↑n + 1) * h) := by
      intro t ht; rw [Set.mem_iUnion]
      exact ⟨⌊(t - t0) / h⌋₊, by constructor <;> nlinarith [Nat.floor_le (div_nonneg (sub_nonneg.mpr ht) h_pos.le), mul_div_cancel₀ (t - t0) h_pos.ne', Nat.lt_floor_add_one ((t - t0) / h), mul_div_cancel₀ (t - t0) h_pos.ne']⟩
    have h_lf : LocallyFinite (fun n : ℕ => Set.Icc (t0 + n * h) (t0 + (↑n + 1) * h)) := by
      intro x
      refine ⟨Set.Ioo (x - 1) (x + 1), Ioo_mem_nhds (by linarith) (by linarith), ?_⟩
      apply Set.Finite.subset (Set.finite_Icc 0 (⌈(x + 1 - t0) / h⌉₊))
      intro n hn
      simp only [Set.mem_setOf_eq] at hn
      obtain ⟨z, hz1, hz2⟩ := hn
      simp only [Set.mem_Icc]; constructor
      · omega
      · by_contra h_neg; push_neg at h_neg
        have : (n : ℝ) * h ≥ (x + 1 - t0) + h := by
          have h7 : (n : ℝ) * h ≥ ((x + 1 - t0) / h + 1) * h :=
            mul_le_mul_of_nonneg_right (by nlinarith [Nat.le_ceil ((x + 1 - t0) / h), (show (n : ℝ) ≥ (⌈(x + 1 - t0) / h⌉₊ : ℝ) + 1 from by exact_mod_cast h_neg)]) h_pos.le
          rw [add_mul, div_mul_cancel₀ _ h_pos.ne'] at h7; linarith
        linarith [hz1.1, hz2.2]
    exact (h_lf.continuousOn_iUnion (fun n => isClosed_Icc) (fun n => eulerPath_continuousOn_Icc v h h_pos t0 y0 n)).mono h_cover

/-
The Euler path has the expected right derivative everywhere.
-/
theorem eulerPath_hasDerivWithinAt {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  (v : ℝ → E → E) (h : ℝ) (h_pos : 0 < h) (t0 : ℝ) (y0 : E) (t : ℝ) (ht : t0 ≤ t) :
  HasDerivWithinAt (eulerPath v h t0 y0) (eulerDeriv v h t0 y0 t) (Set.Ici t) t := by
    -- By definition of $eulerPath$, we know that its right derivative at $t$ is given by $eulerDeriv v h t0 y0 t$.
    have h_right_deriv : ∀ t ≥ t0, HasDerivWithinAt (eulerPath v h t0 y0) (eulerDeriv v h t0 y0 t) (Set.Ioi t) t := by
      intro t ht
      have h_right_deriv : ∀ᶠ t' in nhdsWithin t (Set.Ioi t), eulerPath v h t0 y0 t' = eulerPoint v h t0 y0 (Nat.floor ((t - t0) / h)) + (t' - (t0 + Nat.floor ((t - t0) / h) * h)) • v (t0 + Nat.floor ((t - t0) / h) * h) (eulerPoint v h t0 y0 (Nat.floor ((t - t0) / h))) := by
        refine' eventually_nhdsWithin_iff.mpr _
        filter_upwards [Ioo_mem_nhds (show t > t0 - h by linarith) (show t < t0 + h * (⌊(t - t0) / h⌋₊ + 1) by nlinarith [Nat.lt_floor_add_one ((t - t0) / h), mul_div_cancel₀ (t - t0) h_pos.ne'])] with x hx hx'; simp_all +decide [mul_comm h];
        rw [eulerPath];
        rw [floor_eq_of_mem_Ico h_pos t0 ⌊(t - t0) / h⌋₊ x ⟨by nlinarith [Nat.floor_le (show 0 ≤ (t - t0) / h from div_nonneg (by linarith) h_pos.le), mul_div_cancel₀ (t - t0) h_pos.ne'], by nlinarith [mul_div_cancel₀ (x - t0) h_pos.ne']⟩];
      rw [Filter.EventuallyEq.hasDerivWithinAt_iff] at *
      any_goals tauto
      rw [hasDerivWithinAt_iff_tendsto]; simp +decide [← sub_smul, eulerDeriv]
    exact hasDerivWithinAt_Ioi_iff_Ici.mp (h_right_deriv t ht)

/-
On the interval [t_n, t_{n+1}), the Euler path is given by the affine function starting at y_n with slope v(t_n, y_n).
-/
theorem eulerPath_eq_on_Ico {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  (v : ℝ → E → E) (h : ℝ) (h_pos : 0 < h) (t0 : ℝ) (y0 : E) (n : ℕ)
  (t : ℝ) (ht : t ∈ Set.Ico (t0 + n * h) (t0 + (n + 1) * h)) :
  eulerPath v h t0 y0 t = eulerPoint v h t0 y0 n + (t - (t0 + n * h)) • v (t0 + n * h) (eulerPoint v h t0 y0 n) := by
    simp [eulerPath, floor_eq_of_mem_Ico h_pos t0 n t ht]

/-
On the interval [t_n, t_{n+1}), the Euler derivative is constant and equal to v(t_n, y_n).
-/
theorem eulerDeriv_eq_on_Ico {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  (v : ℝ → E → E) (h : ℝ) (h_pos : 0 < h) (t0 : ℝ) (y0 : E) (n : ℕ)
  (t : ℝ) (ht : t ∈ Set.Ico (t0 + n * h) (t0 + (n + 1) * h)) :
  eulerDeriv v h t0 y0 t = v (t0 + n * h) (eulerPoint v h t0 y0 n) := by
    unfold eulerDeriv; simp [floor_eq_of_mem_Ico h_pos t0 n t ht]

/-
The distance between the Euler point and the Euler path on the interval [t_n, t_{n+1}) is bounded by h * M.
-/
theorem euler_dist_point_path {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  (v : ℝ → E → E) (h : ℝ) (h_pos : 0 < h) (t0 : ℝ) (y0 : E) (n : ℕ)
  (M : ℝ) (v_bound : ∀ t y, ‖v t y‖ ≤ M)
  (t : ℝ) (ht : t ∈ Set.Ico (t0 + n * h) (t0 + (n + 1) * h)) :
  dist (eulerPoint v h t0 y0 n) (eulerPath v h t0 y0 t) ≤ h * M := by
    rw [eulerPath_eq_on_Ico v h h_pos t0 y0 n t ht, dist_eq_norm]
    simp +decide [norm_smul, abs_of_nonneg (sub_nonneg.2 ht.1)]
    exact mul_le_mul (by nlinarith [ht.1, ht.2]) (v_bound _ _) (by positivity) (by positivity)

/-
Bound on the difference between the Euler derivative and the vector field at the Euler path.
-/
theorem euler_derivative_bound {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  (v : ℝ → E → E) (h : ℝ) (h_pos : 0 < h) (t0 : ℝ) (y0 : E) (n : ℕ)
  (K L : NNReal) (M : ℝ)
  (hv : ∀ t, LipschitzWith K (v t))
  (hv_t : ∀ y, LipschitzWith L (fun t => v t y))
  (v_bound : ∀ t y, ‖v t y‖ ≤ M)
  (t : ℝ) (ht : t ∈ Set.Ico (t0 + n * h) (t0 + (n + 1) * h)) :
  dist (eulerDeriv v h t0 y0 t) (v t (eulerPath v h t0 y0 t)) ≤ h * (L + K * M) := by
    -- Using the Lipschitz properties and the bounds we established, we can bound the distances.
    have h1 : dist (v (t0 + n * h) (eulerPoint v h t0 y0 n)) (v t (eulerPoint v h t0 y0 n)) ≤ L * (t - (t0 + n * h)) := by
      simpa only [dist_eq_norm, norm_sub_rev] using
        (hv_t (eulerPoint v h t0 y0 n)).dist_le_mul (t0 + n * h) t |> le_trans <|
        by rw [dist_eq_norm, Real.norm_of_nonpos] <;> linarith [ht.1, ht.2]
    have h2 : dist (v t (eulerPoint v h t0 y0 n)) (v t (eulerPath v h t0 y0 t)) ≤ K * (h * M) :=
      le_trans ((hv t).dist_le_mul _ _)
        (mul_le_mul_of_nonneg_left (euler_dist_point_path v h h_pos t0 y0 n M v_bound t ht) (NNReal.coe_nonneg _))
    -- Using the triangle inequality, we can combine these bounds.
    calc dist (eulerDeriv v h t0 y0 t) (v t (eulerPath v h t0 y0 t))
        = dist (v (t0 + n * h) (eulerPoint v h t0 y0 n)) (v t (eulerPath v h t0 y0 t)) := by
          rw [eulerDeriv_eq_on_Ico v h h_pos t0 y0 n t ht]
      _ ≤ L * (t - (t0 + n * h)) + K * (h * M) := dist_triangle _ _ _ |>.trans (add_le_add h1 h2)
      _ ≤ h * (L + K * M) := by
          have : (0 : ℝ) ≤ L := by positivity
          have : (0 : ℝ) ≤ K * M := mul_nonneg (NNReal.coe_nonneg _) (le_trans (norm_nonneg _) (v_bound t0 y0))
          nlinarith [ht.1, ht.2]

/-
Global bound on the difference between the Euler derivative and the vector field.
-/
theorem euler_derivative_global_bound {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  (v : ℝ → E → E) (h : ℝ) (h_pos : 0 < h) (t0 : ℝ) (y0 : E)
  (K L : NNReal) (M : ℝ)
  (hv : ∀ t, LipschitzWith K (v t))
  (hv_t : ∀ y, LipschitzWith L (fun t => v t y))
  (v_bound : ∀ t y, ‖v t y‖ ≤ M)
  (t : ℝ) (ht : t0 ≤ t) :
  dist (eulerDeriv v h t0 y0 t) (v t (eulerPath v h t0 y0 t)) ≤ h * (L + K * M) := by
    exact euler_derivative_bound v h h_pos t0 y0 _ K L M hv hv_t v_bound t
      ⟨by nlinarith [Nat.floor_le (div_nonneg (sub_nonneg.mpr ht) h_pos.le), mul_div_cancel₀ (t - t0) h_pos.ne'],
       by nlinarith [Nat.lt_floor_add_one ((t - t0) / h), mul_div_cancel₀ (t - t0) h_pos.ne']⟩

/-
Error bound for the Euler method using Gronwall's inequality.
-/
theorem euler_error_bound {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  (v : ℝ → E → E) (h : ℝ) (h_pos : 0 < h) (t0 : ℝ) (y0 : E) (T : ℝ)
  (K L : NNReal) (M : ℝ)
  (hv : ∀ t, LipschitzWith K (v t))
  (hv_t : ∀ y, LipschitzWith L (fun t => v t y))
  (v_bound : ∀ t y, ‖v t y‖ ≤ M)
  (sol : ℝ → E)
  (sol_cont : ContinuousOn sol (Set.Icc t0 T))
  (sol_deriv : ∀ t ∈ Set.Ico t0 T, HasDerivWithinAt sol (v t (sol t)) (Set.Ici t) t)
  (sol_init : sol t0 = y0) :
  ∀ t ∈ Set.Icc t0 T, dist (eulerPath v h t0 y0 t) (sol t) ≤ gronwallBound 0 K (h * (L + K * M)) (t - t0) := by
    intro t ht
    convert dist_le_of_approx_trajectories_ODE hv _ _ _ _ _ _ _ _ _ using 1
    any_goals exact ht
    rotate_left 1
    exact fun t => eulerDeriv v h t0 y0 t
    exact fun t => v t (sol t)
    exact h * (L + K * M); exact 0; exact 0
    exact (eulerPath_continuous v h h_pos t0 y0).mono Set.Icc_subset_Ici_self
    exact fun t ht => eulerPath_hasDerivWithinAt v h h_pos t0 y0 t ht.1
    exact fun t ht => euler_derivative_global_bound v h h_pos t0 y0 K L M hv hv_t v_bound t ht.1
    · exact sol_cont
    · exact sol_deriv
    · simp +decide [dist_self]
    · simp +decide [sol_init]; convert eulerPath_grid_point v h h_pos t0 y0 0; norm_num
    · rw [add_zero]

/-
Convergence of the Euler method to the true solution as the time step goes to zero.
-/
theorem euler_convergence {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  (v : ℝ → E → E) (t0 : ℝ) (y0 : E) (T : ℝ)
  (K L : NNReal) (M : ℝ)
  (hv : ∀ t, LipschitzWith K (v t))
  (hv_t : ∀ y, LipschitzWith L (fun t => v t y))
  (v_bound : ∀ t y, ‖v t y‖ ≤ M)
  (sol : ℝ → E)
  (sol_cont : ContinuousOn sol (Set.Icc t0 T))
  (sol_deriv : ∀ t ∈ Set.Ico t0 T, HasDerivWithinAt sol (v t (sol t)) (Set.Ici t) t)
  (sol_init : sol t0 = y0) :
  ∀ t ∈ Set.Icc t0 T, Filter.Tendsto (fun h => eulerPath v h t0 y0 t) (nhdsWithin 0 (Set.Ioi 0)) (nhds (sol t)) := by
    intro t ht
    -- Since $\epsilon \mapsto \text{gronwallBound } 0\ K\ \epsilon\ (t - t_0)$ is continuous at 0, and takes value 0 at 0, $g(h) \to 0$.
    have h_gronwall_zero : Filter.Tendsto (fun h => gronwallBound 0 K (h * (L + K * M)) (t - t0)) (nhdsWithin 0 (Set.Ioi 0)) (nhds 0) := by
      convert (gronwallBound_continuous_ε _ _ _).continuousWithinAt.tendsto.comp (show Filter.Tendsto (fun h : ℝ => h * (L + K * M)) (nhdsWithin 0 (Set.Ioi 0)) (nhdsWithin 0 (Set.Ici 0)) from ?_) using 2
      · exact (gronwallBound_ε0_δ0 _ _).symm
      · refine' Filter.Tendsto.inf _ _ <;> norm_num
        · exact Continuous.tendsto' (by continuity) _ _ (by simp +decide)
        · exact fun x hx => mul_nonneg hx.le (add_nonneg (NNReal.coe_nonneg _) (mul_nonneg (NNReal.coe_nonneg _) (le_trans (norm_nonneg _) (v_bound t0 y0))))
    exact tendsto_iff_dist_tendsto_zero.mpr (squeeze_zero_norm' (Filter.eventually_of_mem self_mem_nhdsWithin fun x hx => by simpa using euler_error_bound v x hx t0 y0 T K L M hv hv_t v_bound sol sol_cont sol_deriv sol_init t ht) h_gronwall_zero)
